version: '3.9'

services:
  web:
    build: .
    command: python ./main/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/main/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./main/main/.env

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev


volumes:
  postgres_data:
