# Generated by Django 4.0.4 on 2022-05-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_account_first_name_en_account_first_name_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name_ru',
        ),
    ]
